default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: postgres
  password:
  pool: 5

development:
  <<: *default
  database: logs_cli_development

test:
  <<: *default
  database: logs_cli_test

production:
  <<: *default
  database: logs_cli_production

